version: '3'

services:

  db:
    image: postgres:9.5
  db-init:
    build:
      context: .
      dockerfile: docker/db-init/Dockerfile
    depends_on:
    - db

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db