version: '3.3'

services:

  db:
    image: postgres:9.5
  db-init:
    environment:
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_NAME=postgres
      - LOG_LEVEL=error
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres?sslmode=disable
    build:
      context: .
      dockerfile: ./docker/db-init/Dockerfile
    depends_on:
    - db

  app:
    environment:
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_NAME=postgres
      - LOG_LEVEL=error
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres?sslmode=disable
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db