version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15.8
      - image: circleci/postgres:13.2
        environment:
          APP_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: argenti_test
    working_directory: .
    steps:
      - checkout
      - run: go mod tidy
      - run: buffalo plugins install
      - run: buffalo db migrate -e test
      # - run: service postgresql start && buffalo test ./...
    environment:
      DATABASE_URL: "postgres://postgres@localhost:5432/argenti_test?sslmode=disable"
      PORT: 8080
